-- ============================================================
--  PHSN — Procurement System
--  Supabase / PostgreSQL schema + functions
--  Project: ylevtnhbmdftufnhedis  (https://phsn.vercel.app)
-- ============================================================

-- ---------- Extensions ----------
create extension if not exists pgcrypto;

-- ============================================================
--  CORE TABLES
-- ============================================================

-- ---------- Suppliers ----------
create table if not exists suppliers (
  id         bigint generated by default as identity primary key,
  code       text,
  name       text not null,
  contact    text,
  phone      text,
  email      text,
  address    text,
  status     text default 'active',
  created_at timestamptz default now()
);

-- ---------- Products ----------
create table if not exists products (
  id         bigint generated by default as identity primary key,
  name       text not null,
  sku        text,
  category   text,
  unit       text,
  price      numeric default 0,
  min_stock  integer default 0,
  created_at timestamptz default now()
);

-- ---------- Purchase Requests (PR) ----------
create table if not exists requests (
  id           bigint generated by default as identity primary key,
  ref          text,
  item         text,
  qty          numeric,
  unit         text,
  supplier     text,
  unit_price   numeric default 0,
  total        numeric default 0,
  items        jsonb,
  delivery     date,
  project      text,
  notes        text,
  status       text default 'pending',   -- pending | approved | rejected
  po_number    text,                     -- links a PR to its generated PO
  submitted_by text,
  submitted_at timestamptz default now(),
  approved_by  text,
  approved_at  timestamptz
);

-- ---------- Purchase Orders (PO) ----------
create table if not exists purchase_orders (
  id              bigint generated by default as identity primary key,
  po_number       text,
  item            text,
  qty             numeric,
  unit            text,
  supplier        text,
  unit_price      numeric default 0,
  total           numeric default 0,
  items           jsonb,
  delivery        date,
  project         text,
  notes           text,
  delivery_status text default 'issued',  -- issued | partial | received | paid | cancelled
  issued_by       text,
  issued_at       timestamptz default now()
);

-- ---------- Inventory movements ----------
create table if not exists inventory (
  id         bigint generated by default as identity primary key,
  type       text,        -- in | out
  item       text not null,
  qty        numeric,
  ref        text,
  date       date,
  notes      text,
  logged_by  text,
  created_at timestamptz default now()
);

-- ============================================================
--  AUTH / ACCOUNTS
-- ============================================================

-- ---------- User accounts ----------
-- password_hash = sha256( account_no || ':' || password )
create table if not exists app_users (
  id            bigint generated by default as identity primary key,
  account_no    text not null unique,    -- 6-digit login number
  email         text not null unique,
  password_hash text not null,
  name          text not null,
  role          text not null default 'employee',  -- admin | employee
  created_at    timestamptz default now()
);

-- ---------- Login sessions (Phase 1 of security hardening) ----------
create table if not exists app_sessions (
  token_hash text primary key,
  user_id    bigint not null references app_users(id) on delete cascade,
  created_at timestamptz default now(),
  expires_at timestamptz not null
);

-- ============================================================
--  SECURE LOGIN FUNCTIONS  (SECURITY DEFINER)
-- ============================================================

-- Verify account + email + password, issue a session token
create or replace function login(p_account text, p_email text, p_pass text)
returns json language plpgsql security definer set search_path = public, extensions as $$
declare v_user app_users%rowtype; v_token text;
begin
  select * into v_user from app_users
   where account_no = p_account
     and lower(email) = lower(p_email)
     and password_hash = encode(digest(p_account || ':' || p_pass, 'sha256'), 'hex');
  if not found then
    return json_build_object('error','Invalid account number, email or password');
  end if;
  v_token := encode(gen_random_bytes(32), 'hex');
  insert into app_sessions(token_hash, user_id, expires_at)
    values (encode(digest(v_token,'sha256'),'hex'), v_user.id, now() + interval '30 days');
  return json_build_object('token', v_token, 'user', json_build_object(
    'id',v_user.id,'name',v_user.name,'role',v_user.role,
    'account_no',v_user.account_no,'email',v_user.email));
end; $$;

-- Resolve a session token back to its user (used by every other secure function)
-- NB: named app_session_user because session_user is a reserved word in Postgres
create or replace function app_session_user(p_token text)
returns app_users language sql security definer set search_path = public, extensions as $$
  select u.* from app_users u
  join app_sessions s on s.user_id = u.id
  where s.token_hash = encode(digest(p_token,'sha256'),'hex')
    and s.expires_at > now();
$$;

-- End a session
create or replace function logout(p_token text)
returns void language sql security definer set search_path = public, extensions as $$
  delete from app_sessions where token_hash = encode(digest(p_token,'sha256'),'hex');
$$;

grant execute on function login(text,text,text)      to anon, authenticated;
grant execute on function app_session_user(text)     to anon, authenticated;
grant execute on function logout(text)               to anon, authenticated;

-- ============================================================
--  SEED ACCOUNTS (template — set your own hashes/passwords)
--  hash = sha256( account_no || ':' || password )
--  e.g. account 100001, password Mosab@123
-- ============================================================
-- insert into app_users (account_no, email, name, role, password_hash) values
--   ('100001','mosab@phsn.app','Mosab','admin',
--     encode(digest('100001:Mosab@123','sha256'),'hex'))
-- on conflict (account_no) do nothing;

-- ============================================================
--  NOTE: Row-Level Security (RLS) is added in Phase 3 of the
--  security hardening, once the app talks to the database only
--  through the SECURITY DEFINER functions above.
-- ============================================================
